[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/workspace/legal_forms
admin_passwd = admin
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = lawform
http_port = 8069
proxy_mode = True
